FROM <<BASECONTAINER>>

LABEL maintainer="docker@intrepid.de"

USER root
RUN passwd -l root ; \
    apk add --update --upgrade bash curl libtool && \
    apk add --update --upgrade jq

CMD ["/bin/bash"]
